apiVersion: v1
kind: Service
metadata:
  name: bank-loadbalancer
  namespace: default
spec:
  selector:
    app: bank-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
